# Generated by Django 6.0.4 on 2026-05-03 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=350)),
                ('slug', models.SlugField(max_length=100)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_edited'],
                'indexes': [models.Index(fields=['owner'], name='core_projec_owner_i_0532ce_idx'), models.Index(fields=['visibility'], name='core_projec_visibil_d0aad5_idx'), models.Index(fields=['status'], name='core_projec_status_2020cc_idx'), models.Index(fields=['last_edited'], name='core_projec_last_ed_963e74_idx')],
            },
        ),
    ]
